/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: 'var(--surface)',
        'surface-dim': 'var(--surface-dim)',
        'surface-bright': 'var(--surface-bright)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'surface-variant': 'var(--surface-variant)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        primary: 'var(--primary)',
        'on-primary': 'var(--on-primary)',
        secondary: 'var(--secondary)',
        'on-secondary': 'var(--on-secondary)',
        'secondary-container': 'var(--secondary-container)',
        'on-secondary-container': 'var(--on-secondary-container)',
        outline: 'var(--outline)',
        'outline-variant': 'var(--outline-variant)',
        background: 'var(--background)',
        'on-background': 'var(--on-background)',
        cyan: {
          50: 'var(--accent-cyan-50, #ecfeff)',
          100: 'var(--accent-cyan-100, #cffafe)',
          200: 'var(--accent-cyan-200, #a5f3fc)',
          300: 'var(--accent-cyan-300, #67e8f9)',
          400: 'var(--accent-cyan-400, #22d3ee)',
          500: 'var(--accent-cyan-500, #06b6d4)',
          600: 'var(--accent-cyan-600, #0891b2)',
          700: 'var(--accent-cyan-700, #0369a1)',
          800: 'var(--accent-cyan-800, #075985)',
          900: 'var(--accent-cyan-900, #0c4a6e)',
        },
      },
    },
  },
  darkMode: 'class',
  plugins: [],
};
