services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: eaip-postgres
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aeronautical_information_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eaip_network

  minio:
    image: minio/minio
    container_name: ais_minio_server
    restart: unless-stopped
    command: server /data --console-address :9001
    environment:
      - MINIO_ROOT_USER=ais_admin
      - MINIO_ROOT_PASSWORD=AviationData2026!
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /Users/naveendevapalan/ais_data/minio:/data
    networks:
      - eaip_network

  martin:
    image: ghcr.io/maplibre/martin:latest
    container_name: martin
    restart: unless-stopped
    command: --config /config/martin.yaml
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/aeronautical_information_system
      - AWS_ACCESS_KEY_ID=ais_admin
      - AWS_SECRET_ACCESS_KEY=AviationData2026!
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_EC2_METADATA_DISABLED=true
      - AWS_ALLOW_HTTP=true
      - AWS_ENDPOINT=http://minio:9000
      - AWS_ENDPOINT_URL=http://minio:9000
    ports:
      - "3000:3000"
      - "9091:9091"
    volumes:
      - ./backend/martin.yaml:/config/martin.yaml
      - ./backend/data:/data
    depends_on:
      - postgres
      - minio
    networks:
      - eaip_network

  backend:
    image: eaip-backend:latest
    container_name: eaip-backend
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=aeronautical_information_system
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=ais_admin
      - MINIO_SECRET_KEY=AviationData2026!
      - LOG_FORMAT=json
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://alloy:4318/v1/traces
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://alloy:4318/v1/metrics
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - minio
    networks:
      - eaip_network


volumes:
  postgres_data:
    name: cea54d8184a203b630ab55ae2e2429ee565b144cbc8e5430cd5fe4d6dc90c4de
    external: true

networks:
  eaip_network:
    name: eaip_network
    external: true
