receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  faro:
    endpoint: 0.0.0.0:12347
    cors:
      allowed_origins: ["*"]
      allowed_headers: ["*"]

processors:
  batch:
  resource:
    attributes:
      - key: service.name
        from_attribute: service.name
        action: insert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "eaip"

  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"

  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp, faro]
      processors: [batch]
      exporters: [otlp/tempo, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
    logs:
      receivers: [faro]
      processors: [batch]
      exporters: [otlphttp/loki, debug]
