import glob
import json
import os
import shutil
import subprocess
import sys
import time
from datetime import UTC, datetime, timedelta
from pathlib import Path

import numpy as np
import rasterio
import structlog
import xarray as xr
from ecmwf.opendata import Client
from rasterio.transform import from_origin

# Add the backend directory to sys.path to allow 'from app' imports
sys.path.append(str(Path(__file__).parents[2]))

# Set dummy environment variables for required fields not used by this script
# to prevent Pydantic validation errors during standalone runs.
os.environ.setdefault("POSTGRES_PASSWORD", "dummy")
os.environ.setdefault("MINIO_ACCESS_KEY", "dummy")
os.environ.setdefault("MINIO_SECRET_KEY", "dummy")

from app.core.config import settings

logger = structlog.get_logger(__name__)


def _resolve_gdal_cmd() -> str:
    """Resolve the GDAL binary for non-interactive environments like cron/launchd."""
    configured_cmd = settings.GDAL_CMD

    # Respect an explicit absolute/relative path first.
    if os.path.sep in configured_cmd:
        if os.path.isfile(configured_cmd) and os.access(configured_cmd, os.X_OK):
            return configured_cmd
        raise FileNotFoundError(
            f"Configured GDAL command does not exist or is not executable: {configured_cmd}"
        )

    resolved_cmd = shutil.which(configured_cmd)
    if resolved_cmd:
        return resolved_cmd

    fallback_paths = [
        f"/opt/homebrew/bin/{configured_cmd}",
        f"/usr/local/bin/{configured_cmd}",
    ]
    for fallback in fallback_paths:
        if os.path.isfile(fallback) and os.access(fallback, os.X_OK):
            logger.warning(
                "gdal_cmd_resolved_from_fallback",
                configured_cmd=configured_cmd,
                resolved_cmd=fallback,
            )
            return fallback

    raise FileNotFoundError(
        f"Unable to locate GDAL command '{configured_cmd}'. "
        "Set GDAL_CMD to an absolute path or ensure it is available on PATH."
    )


def cleanup_old_files(output_dir: str, manifest_data: dict):
    """Keep only the files referenced in the current manifest."""
    active_files = set()
    if "forecasts" in manifest_data:
        for forecast in manifest_data["forecasts"]:
            if "files" in forecast:
                for url in forecast["files"].values():
                    filename = os.path.basename(url)
                    active_files.add(filename)

    tif_files = glob.glob(os.path.join(output_dir, "wind_*.tif"))
    for f in tif_files:
        basename = os.path.basename(f)
        if basename not in active_files:
            try:
                os.remove(f)
                logger.info("deleted_stale_weather_file", filename=basename)
            except Exception as e:
                logger.error("failed_to_delete_stale_weather_file", filename=f, error=str(e))


def safe_remove_grib(file_path: str):
    """Remove a GRIB file and any associated .idx files created by cfgrib."""
    if not file_path:
        return
    try:
        if os.path.exists(file_path):
            os.remove(file_path)
        # Also remove any .idx files generated by cfgrib (e.g. file.grib2.5b7b6.idx)
        idx_files = glob.glob(f"{file_path}*.idx")
        for idx in idx_files:
            if os.path.exists(idx):
                os.remove(idx)
    except Exception as e:
        logger.error("failed_to_cleanup_temp_grib", path=file_path, error=str(e))


def _get_run_and_steps(now: datetime) -> tuple[int, datetime, list[int]]:
    """
    Determine the most recent available ECMWF run and the forecast steps to
    target a 12-hour valid_time window starting close to "now".

    ECMWF IFS Open Data runs every 6 hours (00, 06, 12, 18 UTC) with a
    ~2-hour publication latency. Forecast steps are available in 3-hour intervals.
    """
    latency_hours = 2
    # The most recent run that has had enough time to be published
    available_now = now - timedelta(hours=latency_hours)
    # Snap to the previous 6-hour cycle (00, 06, 12, 18)
    run_hour = (available_now.hour // 6) * 6
    run_time = available_now.replace(hour=run_hour, minute=0, second=0, microsecond=0)

    # How many hours since that run?
    elapsed_hours = (now - run_time).total_seconds() / 3600
    # Round to nearest 3-hour step, minimum 3
    start_step = max(3, round(elapsed_hours / 3) * 3)

    # 5 steps = 12 hour window (0, +3, +6, +9, +12)
    steps = [start_step + (i * 3) for i in range(5)]

    logger.info(
        "computed_forecast_target",
        run_utc=f"{run_hour:02d}Z",
        steps=steps,
    )
    return run_hour, run_time, steps


def run_pipeline() -> bool:
    logger.info("starting_weather_pipeline")

    os.makedirs(settings.WEATHER_OUTPUT_DIR, exist_ok=True)
    gdal_cmd = _resolve_gdal_cmd()

    now = datetime.now(UTC)
    timestamp_str = now.strftime("%Y%m%d_%H%M%S")

    raw_sfc_file = os.path.join(os.getcwd(), f"temp_sfc_{timestamp_str}.grib2")
    raw_pl_file = os.path.join(os.getcwd(), f"temp_pl_{timestamp_str}.grib2")
    manifest_path = os.path.join(settings.WEATHER_OUTPUT_DIR, "weather_manifest.json")

    run_hour, run_time, steps = _get_run_and_steps(now)

    # --- STEP 1: Download ---
    logger.info("downloading_ecmwf_data", source="azure", run=f"{run_hour:02d}Z", steps=steps)
    client = Client(source="azure")
    try:
        # Surface levels
        client.retrieve(
            time=run_hour,
            step=steps,
            type="fc",
            levtype="sfc",
            param=["10u", "10v"],
            target=raw_sfc_file,
        )

        time.sleep(5)  # Avoid SlowDown error

        # Pressure levels (Single call batch approach to avoid 503 Slow Down)
        client.retrieve(
            time=run_hour,
            step=steps,
            type="fc",
            levtype="pl",
            levelist=[1000, 925, 850, 700, 500, 400, 300, 250, 200, 150],
            param=["u", "v"],
            target=raw_pl_file,
        )
        logger.info("download_complete", num_steps=len(steps))

    except Exception as e:
        logger.error("download_failed", error=str(e))
        safe_remove_grib(raw_sfc_file)
        safe_remove_grib(raw_pl_file)
        return False

    # --- STEP 2: Interpolate & Generate COGs ---
    logger.info("processing_and_interpolating_data")
    manifest_data = {
        "generated_at": now.isoformat().replace("+00:00", "Z"),
        "run_info": {
            "run_hour": run_hour,
            "run_time": run_time.isoformat().replace("+00:00", "Z"),
            "steps": steps,
        },
        "forecasts": [],
    }

    try:
        ds_sfc_raw = xr.open_dataset(raw_sfc_file, engine="cfgrib")
        ds_pl = xr.open_dataset(raw_pl_file, engine="cfgrib")

        # Ensure 'step' is a dimension even if only 1 step was downloaded
        if "step" not in ds_sfc_raw.dims:
            ds_sfc_raw = ds_sfc_raw.expand_dims("step")
        if "step" not in ds_pl.dims:
            ds_pl = ds_pl.expand_dims("step")

        # Altitude mapping for pressure levels (hPa -> approx feet, std atmosphere)
        alt_map = {
            1000: 364,
            925: 2500,
            850: 4781,
            700: 9882,
            500: 18289,
            400: 23564,
            300: 30065,
            250: 33994,
            200: 38662,
            150: 44300,
        }

        # Add altitude coordinate
        ds_combined = ds_pl[["u", "v"]]
        ds_combined = ds_combined.assign_coords(
            altitude=(
                "isobaricInhPa",
                [alt_map[int(float(p))] for p in ds_combined.isobaricInhPa.values],
            )
        )
        ds_combined = ds_combined.swap_dims({"isobaricInhPa": "altitude"})

        # Setup Surface Data (10m)
        ds_sfc = ds_sfc_raw[["u10", "v10"]].rename({"u10": "u", "v10": "v"})
        ds_sfc = ds_sfc.assign_coords(altitude=0).expand_dims("altitude")

        # Drop mismatched coordinates before concatenating
        keep_coords = ["altitude", "latitude", "longitude", "step", "valid_time"]
        ds_combined = ds_combined.drop_vars([c for c in ds_combined.coords if c not in keep_coords])
        ds_sfc = ds_sfc.drop_vars([c for c in ds_sfc.coords if c not in keep_coords])

        ds_combined = xr.concat([ds_sfc, ds_combined], dim="altitude").sortby("altitude")

        # Interpolate to 1000ft intervals
        target_alts = np.arange(0, 40000, 1000)
        ds_interp = ds_combined.interp(altitude=target_alts, method="linear")

        # Export each slice
        # ECMWF Open Data 0.25 degree resolution
        # Grid uses -180 to +179.75 longitude, 90 to -90 latitude.
        transform = from_origin(-180.0, 90.0, 0.25, 0.25)

        for step_idx, step_td in enumerate(ds_interp.step.values):
            # Calculate valid time for this step
            # step_td is typically a timedelta64[ns]
            step_hours = int(step_td.astype("timedelta64[h]").astype(int))
            valid_time = run_time + timedelta(hours=step_hours)

            step_manifest = {
                "valid_time": valid_time.isoformat().replace("+00:00", "Z"),
                "step": step_hours,
                "files": {},
            }

            ds_step = ds_interp.isel(step=step_idx)

            for alt in target_alts:
                alt_slice = ds_step.sel(altitude=alt)
                u_data = alt_slice["u"].values.astype(np.float32)
                v_data = alt_slice["v"].values.astype(np.float32)

                temp_tif = os.path.join(os.getcwd(), f"temp_out_{int(alt)}_{step_hours}.tif")

                # Handle NaNs
                u_data = np.nan_to_num(u_data, nan=0.0)
                v_data = np.nan_to_num(v_data, nan=0.0)

                with rasterio.open(
                    temp_tif,
                    "w",
                    driver="GTiff",
                    height=u_data.shape[0],
                    width=u_data.shape[1],
                    count=2,
                    dtype=u_data.dtype,
                    crs="+proj=latlong",
                    transform=transform,
                    nodata=0.0,
                ) as dst:
                    dst.write(u_data, 1)
                    dst.write(v_data, 2)

                level_name = "surface" if alt == 0 else f"{int(alt // 1000):03d}"
                final_cog_filename = f"wind_{level_name}_{timestamp_str}_step{step_hours:03d}.tif"
                final_cog_path = os.path.join(settings.WEATHER_OUTPUT_DIR, final_cog_filename)

                gdal_args = [
                    gdal_cmd,
                    "-of",
                    "COG",
                    "-ot",
                    "Float32",
                    "-b",
                    "1",
                    "-b",
                    "2",
                    "-projwin",
                    "20",
                    "80",
                    "180",
                    "-10",
                    "-outsize",
                    "640",
                    "360",
                    "-co",
                    "COMPRESS=DEFLATE",
                    "-co",
                    "PREDICTOR=3",
                    temp_tif,
                    final_cog_path,
                ]
                subprocess.run(gdal_args, check=True, capture_output=True, text=True)

                step_manifest["files"][level_name] = (
                    f"{settings.WEATHER_BASE_URL}/{final_cog_filename}"
                )

                os.remove(temp_tif)

            manifest_data["forecasts"].append(step_manifest)

        logger.info("cogs_generated", count=len(target_alts) * len(steps))

    except Exception as e:
        logger.error("processing_failed", error=str(e))
        safe_remove_grib(raw_pl_file)
        safe_remove_grib(raw_sfc_file)
        return False

    # --- STEP 3: Generate Manifest ---
    logger.info("updating_manifest", path=manifest_path)
    temp_manifest = manifest_path + ".tmp"
    try:
        with open(temp_manifest, "w") as f:
            json.dump(manifest_data, f, indent=2)
        os.replace(temp_manifest, manifest_path)
        logger.info("manifest_updated")
    except Exception as e:
        logger.error("manifest_update_failed", error=str(e))

    # --- STEP 4: Cleanup ---
    safe_remove_grib(raw_pl_file)
    safe_remove_grib(raw_sfc_file)

    cleanup_old_files(settings.WEATHER_OUTPUT_DIR, manifest_data)
    logger.info("pipeline_completed_successfully")
    return True


if __name__ == "__main__":
    raise SystemExit(0 if run_pipeline() else 1)
