/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations['health_check_api_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/aerodromes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get All Aerodromes
     * @description Fetches all Aerodrome Reference Points (ARP) from spatial_features and aerodrome_documents.
     *     Returns a GeoJSON FeatureCollection natively from PostGIS.
     */
    get: operations['get_all_aerodromes_api_aerodromes_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/aerodromes/{icao_code}/metadata': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Aerodrome Metadata
     * @description Fetches the JSONB AIP document metadata for a specific aerodrome.
     */
    get: operations['get_aerodrome_metadata_api_aerodromes__icao_code__metadata_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/aerodromes/{icao_code}/section/{section_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Aerodrome Section
     * @description Returns a specific AIP sub-section for an aerodrome.
     */
    get: operations['get_aerodrome_section_api_aerodromes__icao_code__section__section_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Global Search
     * @description Searches across Aerodromes, NavAids, Waypoints, and ATS Routes.
     *     Calculates geographic center and bounding boxes for LineStrings
     *     so the frontend can frame them on click.
     */
    get: operations['global_search_api_search_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/aerodromes/{icao_code}/charts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Aerodrome Charts
     * @description Returns the list of available aerodrome charts for a given ICAO code.
     */
    get: operations['get_aerodrome_charts_api_aerodromes__icao_code__charts_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/proxy-pdf': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Proxy Pdf
     * @description Proxies a remote PDF through the backend so the frontend can render it
     *     in an iframe without CORS issues.
     */
    get: operations['proxy_pdf_api_proxy_pdf_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/features/{icao_code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Aerodrome Features
     * @description Fetches 3D spatial features (obstacles, buildings) for a specific aerodrome.
     *     Returns a GeoJSON FeatureCollection natively from PostGIS.
     */
    get: operations['get_aerodrome_features_api_features__icao_code__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/weather/{icao_code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Weather
     * @description Returns live METAR and TAF for a given ICAO airport code.
     *
     *     Scrapes both Chennai and Delhi OLBS concurrently for redundancy.
     *     Returns the freshest data; falls back to whichever source is available.
     *     Data is cached in-memory for 5 minutes.
     */
    get: operations['get_weather_api_weather__icao_code__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/notams/{icao_code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Notams By Airport
     * @description Returns all NOTAMs for a specific airport ICAO code, ordered by valid_from DESC.
     */
    get: operations['get_notams_by_airport_api_notams__icao_code__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/notams': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get All Notams
     * @description Returns NOTAMs with optional filters. Without params, returns all NOTAMs.
     */
    get: operations['get_all_notams_api_notams_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/notams/fir/{fir_code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Notams By Fir
     * @description Returns all NOTAMs for a specific FIR (e.g., VOMF, VABF).
     */
    get: operations['get_notams_by_fir_api_notams_fir__fir_code__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/daylight/{icao_code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Daylight
     * @description Returns daylight/twilight data for a given airport.
     *
     *     - No params → returns all records for the current month.
     *     - `?month=3` → returns all days in March.
     *     - `?date=2026-03-18` → returns a single day.
     */
    get: operations['get_daylight_api_daylight__icao_code__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/ats-route-labels': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Ats Route Labels
     * @description Returns the midpoints of all ATS route segments as GeoJSON points.
     *     Includes route_id, route_type, and the segment bearing for labeling.
     */
    get: operations['get_ats_route_labels_api_ats_route_labels_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AerodromeSectionResponse */
    AerodromeSectionResponse: {
      /** Section Id */
      section_id: string;
      /** Title */
      title: string;
      /** Data Type */
      data_type: string;
      /** Data */
      data?:
        | {
            [key: string]: unknown;
          }
        | unknown[]
        | null;
    };
    /** ChartResponse */
    ChartResponse: {
      /** Chart Id */
      chart_id: number;
      /** Chart Title */
      chart_title?: string | null;
      /** Chart Index */
      chart_index?: string | null;
      /** Chart Url */
      chart_url?: string | null;
    };
    /** DaylightRecord */
    DaylightRecord: {
      /** Date */
      date: string;
      /** Twilight From */
      twilight_from?: string | null;
      /** Sunrise */
      sunrise?: string | null;
      /** Sunset */
      sunset?: string | null;
      /** Twilight To */
      twilight_to?: string | null;
    };
    /** DaylightResponse */
    DaylightResponse: {
      /** Airport Icao */
      airport_icao: string;
      /** Airport Name */
      airport_name: string;
      /**
       * Records
       * @default []
       */
      records: components['schemas']['DaylightRecord'][];
    };
    /** GeoJsonFeature */
    GeoJsonFeature: {
      /**
       * Type
       * @default Feature
       */
      type: string;
      /** Geometry */
      geometry?: {
        [key: string]: unknown;
      } | null;
      /** Properties */
      properties?: {
        [key: string]: unknown;
      } | null;
    };
    /** GeoJsonFeatureCollection */
    GeoJsonFeatureCollection: {
      /**
       * Type
       * @default FeatureCollection
       */
      type: string;
      /** Features */
      features?: components['schemas']['GeoJsonFeature'][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** NotamResponse */
    NotamResponse: {
      /** Notam Id */
      notam_id: string;
      /** Source File */
      source_file: string;
      /** Series */
      series?: string | null;
      /** Scope */
      scope?: string | null;
      /** Fir */
      fir?: string | null;
      /** Combined Fir */
      combined_fir?: string | null;
      /** Airport Icao */
      airport_icao?: string | null;
      /** Valid From */
      valid_from?: string | null;
      /** Valid To */
      valid_to?: string | null;
      /** Is Permanent */
      is_permanent?: boolean | null;
      /** Is Estimated */
      is_estimated?: boolean | null;
      /** Duration Category */
      duration_category?: string | null;
      /** Description */
      description?: string | null;
    };
    /** SearchResultResponse */
    SearchResultResponse: {
      /** Id */
      id: string;
      /** Name */
      name?: string | null;
      /** Type */
      type: string;
      /** Center */
      center?: number[] | null;
      /** Bounds */
      bounds?: number[] | null;
      /** Route Type */
      route_type?: string | null;
      /** Properties */
      properties?: {
        [key: string]: unknown;
      } | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WeatherResponse */
    WeatherResponse: {
      /** Icao */
      icao: string;
      /** Metar */
      metar?: string | null;
      /**
       * Taf
       * @default []
       */
      taf: string[][];
      /** Source */
      source?: string | null;
      /** Fetched At */
      fetched_at?: string | null;
      /**
       * Sources Available
       * @default []
       */
      sources_available: string[];
      /**
       * Cached
       * @default false
       */
      cached: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_check_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  get_all_aerodromes_api_aerodromes_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GeoJsonFeatureCollection'];
        };
      };
    };
  };
  get_aerodrome_metadata_api_aerodromes__icao_code__metadata_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        icao_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_aerodrome_section_api_aerodromes__icao_code__section__section_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        icao_code: string;
        section_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AerodromeSectionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  global_search_api_search_get: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SearchResultResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_aerodrome_charts_api_aerodromes__icao_code__charts_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        icao_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChartResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_pdf_api_proxy_pdf_get: {
    parameters: {
      query: {
        /** @description Remote PDF URL to proxy */
        url: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_aerodrome_features_api_features__icao_code__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        icao_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GeoJsonFeatureCollection'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_weather_api_weather__icao_code__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        icao_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WeatherResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_notams_by_airport_api_notams__icao_code__get: {
    parameters: {
      query?: {
        /** @description If true, return only currently active NOTAMs */
        active_only?: boolean;
      };
      header?: never;
      path: {
        icao_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotamResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_all_notams_api_notams_get: {
    parameters: {
      query?: {
        /** @description Filter by airport ICAO code */
        icao?: string | null;
        /** @description If true, return only currently active NOTAMs */
        active_only?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotamResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_notams_by_fir_api_notams_fir__fir_code__get: {
    parameters: {
      query?: {
        /** @description If true, return only currently active NOTAMs */
        active_only?: boolean;
      };
      header?: never;
      path: {
        fir_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotamResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_daylight_api_daylight__icao_code__get: {
    parameters: {
      query?: {
        /** @description Filter by month (1-12). Defaults to current month. */
        month?: number | null;
        /** @description Filter by specific date (YYYY-MM-DD) */
        date?: string | null;
      };
      header?: never;
      path: {
        icao_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DaylightResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_ats_route_labels_api_ats_route_labels_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GeoJsonFeatureCollection'];
        };
      };
    };
  };
}
