apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eaip-frontend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "3"
    spec:
      serviceAccountName: eaip-github-actions@project-d5038013-e773-4f0b-98a.iam.gserviceaccount.com
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: __IMAGE__
          ports:
            - containerPort: 8080
              name: http1
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
  traffic:
    - latestRevision: true
      percent: 100
