apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eaip-martin
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/network-interfaces: '[{"network":"default"}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      serviceAccountName: eaip-github-actions@project-d5038013-e773-4f0b-98a.iam.gserviceaccount.com
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
        - image: __IMAGE__
          args:
            - --config
            - /mnt/gcs/martin.yaml
          ports:
            - containerPort: 3000
              name: http1
          env:
            - name: DATABASE_URL
              value: "__MARTIN_DATABASE_URL__"
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - mountPath: /mnt/gcs
              name: gcs-volume
      volumes:
        - name: gcs-volume
          csi:
            driver: gcsfuse.run.googleapis.com
            volumeAttributes:
              bucketName: eaip-staging-data-project-d5038013-e773-4f0b-98a
  traffic:
    - latestRevision: true
      percent: 100
